"""Seed content migrated verbatim from the original SkillLoop project."""

COURSES = [
    ("front-end-web-development-fundamentals", "Front-End Web Development Fundamentals", "Web Development",
     "Build and deploy responsive websites using HTML, CSS and JavaScript.",
     "A structured introduction to building for the web. You will write semantic HTML, style responsive layouts with modern CSS, add interactivity with JavaScript, and publish a portfolio site by the end of the programme.",
     "Beginner", 8, "Anita Deshpande", "Senior Front-End Engineer",
     "Ten years building consumer web products; previously led the front-end guild at a Pune-based product studio."),
    ("introduction-to-graphic-design", "Introduction to Graphic Design with Canva & Figma", "Graphic Design",
     "Learn layout, typography and brand basics using industry tools.",
     "Design fundamentals taught through practical briefs. Covers composition, colour theory, typographic hierarchy, and delivery of print and digital assets using Canva and Figma.",
     "Beginner", 6, "Rahul Menon", "Design Lead",
     "Brand and product designer with a decade of agency experience across FMCG and public-sector campaigns."),
    ("digital-marketing-social-media-essentials", "Digital Marketing & Social Media Essentials", "Digital Marketing",
     "Plan, run and measure campaigns across search and social.",
     "From audience research to reporting. Learn content planning, paid social basics, search fundamentals, and how to read an analytics dashboard and defend a budget.",
     "Intermediate", 6, "Fatima Sheikh", "Growth Marketing Consultant",
     "Former performance marketing manager; has run acquisition budgets for three funded D2C brands."),
    ("ms-office-for-the-workplace", "MS Office for the Workplace", "MS Office",
     "Practical Word, Excel and PowerPoint skills employers test for.",
     "Workplace-ready document, spreadsheet and presentation skills. Includes formulas, pivot tables, mail merge, and formatting standards used in corporate reporting.",
     "Beginner", 4, "Joseph Kariuki", "Corporate Trainer",
     "Delivers workplace productivity training to public-sector and BPO teams."),
    ("ai-tools-for-everyday-productivity", "AI Tools for Everyday Productivity", "AI Basics",
     "Use AI assistants responsibly for research, writing and analysis.",
     "A grounded introduction to generative AI at work. Covers prompt construction, verification habits, document and data workflows, and the limits and ethics of AI-assisted output.",
     "Beginner", 4, "Priya Nair", "Applied AI Instructor",
     "Data scientist turned educator, focused on practical AI literacy for non-technical roles."),
]

CATEGORIES = ["Web Development", "Graphic Design", "Digital Marketing", "MS Office", "AI Basics"]

LESSONS = [
    ("front-end-web-development-fundamentals", "How the Web Works", "video", 14, 1, "Clients, servers, DNS and what actually happens when a page loads."),
    ("front-end-web-development-fundamentals", "Semantic HTML Structure", "video", 18, 2, "Document outlines, landmarks and accessible markup."),
    ("front-end-web-development-fundamentals", "CSS Layout: Flexbox and Grid", "video", 22, 3, "Building responsive layouts without hacks."),
    ("front-end-web-development-fundamentals", "Reference: CSS Layout Cheatsheet", "pdf", 10, 4, "A printable summary of layout properties and use cases."),
    ("front-end-web-development-fundamentals", "JavaScript Fundamentals", "video", 26, 5, "Variables, functions, arrays and the DOM."),
    ("front-end-web-development-fundamentals", "Deploying Your Portfolio", "video", 16, 6, "Version control basics and publishing to a static host."),
    ("introduction-to-graphic-design", "Design Principles and Composition", "video", 15, 1, "Balance, contrast, alignment and repetition in practice."),
    ("introduction-to-graphic-design", "Typography for Beginners", "video", 18, 2, "Choosing typefaces and setting readable hierarchy."),
    ("introduction-to-graphic-design", "Colour Theory in Application", "video", 14, 3, "Building palettes that survive real-world printing and screens."),
    ("introduction-to-graphic-design", "Reference: Brand Asset Checklist", "pdf", 8, 4, "What to deliver when handing off a small brand system."),
    ("introduction-to-graphic-design", "Figma Workflow Essentials", "video", 20, 5, "Frames, components and shared libraries."),
    ("digital-marketing-social-media-essentials", "Audience Research and Positioning", "video", 16, 1, "Defining who you are speaking to before you spend."),
    ("digital-marketing-social-media-essentials", "Content Planning and Calendars", "video", 14, 2, "Building a sustainable publishing rhythm."),
    ("digital-marketing-social-media-essentials", "Paid Social Fundamentals", "video", 20, 3, "Campaign structure, targeting and creative testing."),
    ("digital-marketing-social-media-essentials", "Reference: Campaign Reporting Template", "pdf", 9, 4, "A reporting structure you can reuse with clients."),
    ("digital-marketing-social-media-essentials", "Measuring What Matters", "video", 18, 5, "Attribution basics and avoiding vanity metrics."),
    ("ms-office-for-the-workplace", "Professional Documents in Word", "video", 15, 1, "Styles, templates and mail merge."),
    ("ms-office-for-the-workplace", "Excel Formulas and Functions", "video", 22, 2, "Lookup, logic and text functions used daily."),
    ("ms-office-for-the-workplace", "Pivot Tables and Charts", "video", 18, 3, "Summarising data for management reporting."),
    ("ms-office-for-the-workplace", "Reference: Excel Shortcut Sheet", "pdf", 6, 4, "Keyboard shortcuts that measurably speed up work."),
    ("ms-office-for-the-workplace", "Presentations That Hold Attention", "video", 14, 5, "Slide structure, restraint and delivery."),
    ("ai-tools-for-everyday-productivity", "What Generative AI Can and Cannot Do", "video", 13, 1, "A realistic mental model of current systems."),
    ("ai-tools-for-everyday-productivity", "Writing Effective Prompts", "video", 17, 2, "Context, constraints and iteration."),
    ("ai-tools-for-everyday-productivity", "Verification and Responsible Use", "video", 15, 3, "Checking output and handling sensitive information."),
    ("ai-tools-for-everyday-productivity", "Reference: Workplace AI Policy Primer", "pdf", 7, 4, "Questions to ask before using AI on company data."),
]

QUIZZES = [
    ("front-end-web-development-fundamentals", "Front-End Fundamentals Assessment", "Covers HTML structure, CSS layout and core JavaScript concepts.", 60, 10),
    ("introduction-to-graphic-design", "Design Fundamentals Assessment", "Covers composition, typography and colour theory.", 60, 8),
    ("digital-marketing-social-media-essentials", "Digital Marketing Assessment", "Covers audience research, campaign structure and measurement.", 60, 8),
    ("ms-office-for-the-workplace", "Workplace MS Office Assessment", "Covers Word, Excel formulas and presentation practice.", 60, 8),
    ("ai-tools-for-everyday-productivity", "AI Literacy Assessment", "Covers capabilities, prompting and responsible use.", 60, 8),
]

QUESTIONS = [
    ("front-end-web-development-fundamentals", 1, "Which element best describes the main navigation region of a page?",
     ['<div class="nav">', "<nav>", "<section>", "<aside>"], 1),
    ("front-end-web-development-fundamentals", 2, "Which CSS layout method is designed for one-dimensional alignment?",
     ["Grid", "Float", "Flexbox", "Table"], 2),
    ("front-end-web-development-fundamentals", 3, 'What does the "box-sizing: border-box" declaration do?',
     ["Includes padding and border in the element width", "Removes all margins", "Adds a visible border", "Centres the element"], 0),
    ("front-end-web-development-fundamentals", 4, "Which method selects a single element by CSS selector in JavaScript?",
     ["document.getElements()", "document.querySelector()", "document.selectAll()", "document.find()"], 1),
    ("front-end-web-development-fundamentals", 5, "A media query is primarily used to:",
     ["Load video files", "Apply styles conditionally by viewport", "Compress images", "Validate forms"], 1),
    ("introduction-to-graphic-design", 1, "Visual hierarchy is primarily achieved through:",
     ["Using more colours", "Contrast, scale and spacing", "Adding more text", "Centring everything"], 1),
    ("introduction-to-graphic-design", 2, "Kerning refers to:",
     ["Space between individual letters", "Line height", "Paragraph indentation", "Font weight"], 0),
    ("introduction-to-graphic-design", 3, "Which colour model is used for print production?",
     ["RGB", "HSL", "CMYK", "HEX"], 2),
    ("introduction-to-graphic-design", 4, "In Figma, a component is best described as:",
     ["A single exported image", "A reusable design element with instances", "A colour swatch", "A comment thread"], 1),
    ("digital-marketing-social-media-essentials", 1, "A buyer persona is used to:",
     ["Set the advertising budget", "Describe a representative target customer", "Design the logo", "Measure page speed"], 1),
    ("digital-marketing-social-media-essentials", 2, "Click-through rate is calculated as:",
     ["Clicks divided by impressions", "Impressions divided by clicks", "Spend divided by clicks", "Conversions divided by spend"], 0),
    ("digital-marketing-social-media-essentials", 3, "Which is a vanity metric in most campaigns?",
     ["Cost per acquisition", "Follower count", "Conversion rate", "Return on ad spend"], 1),
    ("digital-marketing-social-media-essentials", 4, "A/B testing requires:",
     ["Changing several variables at once", "Isolating one variable between variants", "Running for one hour", "Using only organic traffic"], 1),
    ("ms-office-for-the-workplace", 1, "Which Excel function returns a value from a table by matching a key?",
     ["CONCAT", "VLOOKUP", "TRIM", "TODAY"], 1),
    ("ms-office-for-the-workplace", 2, "A pivot table is primarily used to:",
     ["Format cells", "Summarise and group large datasets", "Print worksheets", "Protect a workbook"], 1),
    ("ms-office-for-the-workplace", 3, "Mail merge in Word is used to:",
     ["Send email attachments", "Generate personalised documents from a data source", "Merge two documents into one", "Compress a file"], 1),
    ("ms-office-for-the-workplace", 4, "Absolute cell reference in Excel is written as:",
     ["A1", "$A$1", "A$", "#A1"], 1),
    ("ai-tools-for-everyday-productivity", 1, "A language model generates responses by:",
     ["Searching a verified database", "Predicting likely text from patterns", "Copying from a fixed answer list", "Running a spreadsheet formula"], 1),
    ("ai-tools-for-everyday-productivity", 2, '"Hallucination" in AI output means:',
     ["A rendering error", "Confident but factually incorrect content", "A slow response", "An encrypted answer"], 1),
    ("ai-tools-for-everyday-productivity", 3, "A well-constructed prompt usually includes:",
     ["Only a single keyword", "Context, task and constraints", "All capital letters", "Multiple unrelated questions"], 1),
    ("ai-tools-for-everyday-productivity", 4, "Before pasting company data into a public AI tool you should:",
     ["Check your organisation's data policy", "Translate it first", "Convert it to PDF", "Nothing, it is always safe"], 0),
]

JOBS = [
    ("Junior Front-End Developer", "Meridian Digital Systems", "Bengaluru, India", "Full-time", "Web Development", "Rs 4.2 - 6.0 LPA",
     "Join a six-person product team building customer dashboards. You will implement responsive interfaces from design files and take ownership of small features end to end.",
     ["HTML, CSS and JavaScript proficiency", "Familiarity with a component framework", "Understanding of responsive design", "Portfolio of at least two projects"],
     "Meridian Digital Systems builds workflow software for logistics operators across South Asia. Founded 2016, 140 employees.", "2026-07-28"),
    ("Web Development Intern", "Northline Technologies", "Remote", "Internship", "Web Development", "Rs 15,000 / month",
     "A six-month structured internship with weekly mentorship. Contribute to internal tooling and the public marketing site.",
     ["Completed a front-end course or equivalent", "Basic version control knowledge", "Available 30 hours per week"],
     "Northline Technologies is a services firm delivering web and cloud projects for mid-market clients.", "2026-08-02"),
    ("Graphic Designer", "Anvaya Brand Studio", "Pune, India", "Full-time", "Graphic Design", "Rs 3.6 - 5.4 LPA",
     "Produce social, print and packaging assets for retail clients. Work directly with the design lead on brand refresh projects.",
     ["Figma and Adobe Creative Suite", "Strong typographic sense", "Portfolio demonstrating brand work", "Ability to take structured feedback"],
     "Anvaya Brand Studio is an independent branding practice working with food, retail and cultural clients.", "2026-07-19"),
    ("Social Media Executive", "Kavach Consumer Goods", "Hyderabad, India", "Full-time", "Digital Marketing", "Rs 3.0 - 4.5 LPA",
     "Own the day-to-day publishing calendar across three brand handles and report weekly on engagement and reach.",
     ["Content planning experience", "Comfort with analytics dashboards", "Clear written English", "Basic design tool familiarity"],
     "Kavach Consumer Goods manufactures household care products distributed across nine states.", "2026-08-05"),
    ("Digital Marketing Associate", "Brightpath Learning", "Remote", "Contract", "Digital Marketing", "Rs 35,000 / month",
     "Support paid acquisition for an education client. Manage campaign setup, creative rotation and monthly reporting.",
     ["Understanding of paid social platforms", "Spreadsheet reporting skills", "Attention to budget detail"],
     "Brightpath Learning is an online skills provider serving 40,000 learners.", "2026-07-30"),
    ("Office Administrator", "Sundar Infra Projects", "Chennai, India", "Full-time", "MS Office", "Rs 2.8 - 3.6 LPA",
     "Maintain project documentation, prepare weekly management reports and coordinate site correspondence.",
     ["Advanced Excel including pivot tables", "Professional document formatting", "Organised record keeping"],
     "Sundar Infra Projects delivers civil infrastructure contracts for state and private clients.", "2026-08-08"),
    ("Data Entry & Reporting Assistant", "Civicline Services", "Nagpur, India", "Part-time", "MS Office", "Rs 18,000 / month",
     "Process intake records and produce standardised weekly reports for programme managers.",
     ["Accurate data entry", "Excel formulas", "Confidentiality awareness"],
     "Civicline Services administers citizen-facing programmes on behalf of public bodies.", "2026-08-01"),
    ("AI Operations Assistant", "Trellis Analytics", "Remote", "Full-time", "AI Basics", "Rs 4.8 - 6.5 LPA",
     "Support analysts by preparing documents, running assisted research workflows and verifying AI-generated summaries.",
     ["Comfort using AI assistants", "Strong verification habits", "Clear written communication", "Basic spreadsheet skills"],
     "Trellis Analytics provides research and reporting services to consulting firms.", "2026-08-06"),
]
